# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/terrainrlScenarios
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlScenarios.so
  DEFINES   += -DDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../scenarios -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlLearning -lterrainrlAnim -lterrainrlSim -lterrainrlUtil -lterrainrlRender -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_debug -lBulletCollision_gmake_x64_debug -lLinearMath_gmake_x64_debug -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlLearning.so ../lib/libterrainrlAnim.so ../lib/libterrainrlSim.so ../lib/libterrainrlUtil.so ../lib/libterrainrlRender.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/terrainrlScenarios
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlScenarios.so
  DEFINES   += -DNDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../scenarios -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -O2 -m32 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlLearning -lterrainrlAnim -lterrainrlSim -lterrainrlUtil -lterrainrlRender -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_release -lBulletCollision_gmake_x64_release -lLinearMath_gmake_x64_release -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlLearning.so ../lib/libterrainrlAnim.so ../lib/libterrainrlSim.so ../lib/libterrainrlUtil.so ../lib/libterrainrlRender.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/terrainrlScenarios
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlScenarios.so
  DEFINES   += -DDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../scenarios -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlLearning -lterrainrlAnim -lterrainrlSim -lterrainrlUtil -lterrainrlRender -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_debug -lBulletCollision_gmake_x64_debug -lLinearMath_gmake_x64_debug -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlLearning.so ../lib/libterrainrlAnim.so ../lib/libterrainrlSim.so ../lib/libterrainrlUtil.so ../lib/libterrainrlRender.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/terrainrlScenarios
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlScenarios.so
  DEFINES   += -DNDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../scenarios -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -O2 -m64 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlLearning -lterrainrlAnim -lterrainrlSim -lterrainrlUtil -lterrainrlRender -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_release -lBulletCollision_gmake_x64_release -lLinearMath_gmake_x64_release -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlLearning.so ../lib/libterrainrlAnim.so ../lib/libterrainrlSim.so ../lib/libterrainrlUtil.so ../lib/libterrainrlRender.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/DrawScenarioImitate.o \
	$(OBJDIR)/ScenarioHackMultChar.o \
	$(OBJDIR)/DrawScenarioSimChar.o \
	$(OBJDIR)/DrawScenarioTrainDMACE.o \
	$(OBJDIR)/ScenarioExpMimicRNN.o \
	$(OBJDIR)/DrawScenarioTrainDPG.o \
	$(OBJDIR)/ScenarioTrainMACE.o \
	$(OBJDIR)/ScenarioExpDPG.o \
	$(OBJDIR)/DrawScenarioTrackMotion.o \
	$(OBJDIR)/ScenarioTrackMotion.o \
	$(OBJDIR)/ScenarioExpHike.o \
	$(OBJDIR)/ScenarioImitate.o \
	$(OBJDIR)/ScenarioExpSoccer.o \
	$(OBJDIR)/DrawScenarioKinMotion.o \
	$(OBJDIR)/ScenarioTrainLoco.o \
	$(OBJDIR)/ScenarioExpMimic.o \
	$(OBJDIR)/ScenarioTerrainViewer.o \
	$(OBJDIR)/DrawScenarioTrainSoccer.o \
	$(OBJDIR)/ScenarioTrainCaclaDV.o \
	$(OBJDIR)/DrawScenarioTrainCaclaDV.o \
	$(OBJDIR)/ScenarioPoliEval.o \
	$(OBJDIR)/DrawScenarioMimicEval.o \
	$(OBJDIR)/DrawScenarioSimInteractive.o \
	$(OBJDIR)/DrawScenario.o \
	$(OBJDIR)/DrawScenarioImitateEval.o \
	$(OBJDIR)/DrawScenarioSoccerEval.o \
	$(OBJDIR)/DrawScenarioMimicRNN.o \
	$(OBJDIR)/ScenarioExpDMACE.o \
	$(OBJDIR)/ScenarioVelCtrl.o \
	$(OBJDIR)/DrawScenarioImitateTargetEval.o \
	$(OBJDIR)/ScenarioExpImitateStep.o \
	$(OBJDIR)/DrawScenarioHikeEval.o \
	$(OBJDIR)/ScenarioExpImitate.o \
	$(OBJDIR)/DrawScenarioTrainLoco.o \
	$(OBJDIR)/ScenarioImitateEval.o \
	$(OBJDIR)/DrawScenarioTrainCacla.o \
	$(OBJDIR)/ScenarioClimb.o \
	$(OBJDIR)/ScenarioLocoEval.o \
	$(OBJDIR)/ScenarioMimicRNN.o \
	$(OBJDIR)/DrawScenarioPoliEval.o \
	$(OBJDIR)/ScenarioExpCacla.o \
	$(OBJDIR)/ScenarioTrain.o \
	$(OBJDIR)/DrawScenarioVelCtrl.o \
	$(OBJDIR)/DrawScenarioJump.o \
	$(OBJDIR)/DrawScenarioHackMultChar.o \
	$(OBJDIR)/ScenarioMimic.o \
	$(OBJDIR)/DrawScenarioMimic.o \
	$(OBJDIR)/ScenarioImitateTarget.o \
	$(OBJDIR)/ScenarioExpMACEDPG.o \
	$(OBJDIR)/DrawScenarioImitateTarget.o \
	$(OBJDIR)/DrawScenarioTrain.o \
	$(OBJDIR)/ScenarioMimicEval.o \
	$(OBJDIR)/ScenarioExp.o \
	$(OBJDIR)/ScenarioTrainCacla.o \
	$(OBJDIR)/ScenarioImitateStepEval.o \
	$(OBJDIR)/ScenarioSimChar.o \
	$(OBJDIR)/ScenarioKinMotion.o \
	$(OBJDIR)/ScenarioExpLoco.o \
	$(OBJDIR)/ScenarioTrainMACEDPG.o \
	$(OBJDIR)/DrawScenarioTerrainRL.o \
	$(OBJDIR)/ScenarioHikeEval.o \
	$(OBJDIR)/ScenarioTrainDMACE.o \
	$(OBJDIR)/ScenarioSoccerEval.o \
	$(OBJDIR)/DrawScenarioTrainMACEDPG.o \
	$(OBJDIR)/DrawScenarioTerrainViewer.o \
	$(OBJDIR)/DrawScenarioImitateStepEval.o \
	$(OBJDIR)/Scenario.o \
	$(OBJDIR)/DrawScenarioTrainMACE.o \
	$(OBJDIR)/ScenarioTrainHike.o \
	$(OBJDIR)/ScenarioJump.o \
	$(OBJDIR)/DrawScenarioClimb.o \
	$(OBJDIR)/DrawScenarioImitateStep.o \
	$(OBJDIR)/ScenarioTrainDPG.o \
	$(OBJDIR)/ScenarioExpMACE.o \
	$(OBJDIR)/DrawScenarioLocoEval.o \
	$(OBJDIR)/ScenarioTrainSoccer.o \
	$(OBJDIR)/ScenarioExpImitateTarget.o \
	$(OBJDIR)/ScenarioImitateTargetEval.o \
	$(OBJDIR)/DrawScenarioTrainHike.o \
	$(OBJDIR)/ScenarioImitateStep.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking terrainrlScenarios
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning terrainrlScenarios
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/DrawScenarioImitate.o: ../scenarios/DrawScenarioImitate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioHackMultChar.o: ../scenarios/ScenarioHackMultChar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioSimChar.o: ../scenarios/DrawScenarioSimChar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainDMACE.o: ../scenarios/DrawScenarioTrainDMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpMimicRNN.o: ../scenarios/ScenarioExpMimicRNN.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainDPG.o: ../scenarios/DrawScenarioTrainDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainMACE.o: ../scenarios/ScenarioTrainMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpDPG.o: ../scenarios/ScenarioExpDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrackMotion.o: ../scenarios/DrawScenarioTrackMotion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrackMotion.o: ../scenarios/ScenarioTrackMotion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpHike.o: ../scenarios/ScenarioExpHike.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitate.o: ../scenarios/ScenarioImitate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpSoccer.o: ../scenarios/ScenarioExpSoccer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioKinMotion.o: ../scenarios/DrawScenarioKinMotion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainLoco.o: ../scenarios/ScenarioTrainLoco.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpMimic.o: ../scenarios/ScenarioExpMimic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTerrainViewer.o: ../scenarios/ScenarioTerrainViewer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainSoccer.o: ../scenarios/DrawScenarioTrainSoccer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainCaclaDV.o: ../scenarios/ScenarioTrainCaclaDV.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainCaclaDV.o: ../scenarios/DrawScenarioTrainCaclaDV.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioPoliEval.o: ../scenarios/ScenarioPoliEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioMimicEval.o: ../scenarios/DrawScenarioMimicEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioSimInteractive.o: ../scenarios/DrawScenarioSimInteractive.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenario.o: ../scenarios/DrawScenario.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioImitateEval.o: ../scenarios/DrawScenarioImitateEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioSoccerEval.o: ../scenarios/DrawScenarioSoccerEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioMimicRNN.o: ../scenarios/DrawScenarioMimicRNN.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpDMACE.o: ../scenarios/ScenarioExpDMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioVelCtrl.o: ../scenarios/ScenarioVelCtrl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioImitateTargetEval.o: ../scenarios/DrawScenarioImitateTargetEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpImitateStep.o: ../scenarios/ScenarioExpImitateStep.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioHikeEval.o: ../scenarios/DrawScenarioHikeEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpImitate.o: ../scenarios/ScenarioExpImitate.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainLoco.o: ../scenarios/DrawScenarioTrainLoco.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitateEval.o: ../scenarios/ScenarioImitateEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainCacla.o: ../scenarios/DrawScenarioTrainCacla.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioClimb.o: ../scenarios/ScenarioClimb.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioLocoEval.o: ../scenarios/ScenarioLocoEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioMimicRNN.o: ../scenarios/ScenarioMimicRNN.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioPoliEval.o: ../scenarios/DrawScenarioPoliEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpCacla.o: ../scenarios/ScenarioExpCacla.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrain.o: ../scenarios/ScenarioTrain.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioVelCtrl.o: ../scenarios/DrawScenarioVelCtrl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioJump.o: ../scenarios/DrawScenarioJump.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioHackMultChar.o: ../scenarios/DrawScenarioHackMultChar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioMimic.o: ../scenarios/ScenarioMimic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioMimic.o: ../scenarios/DrawScenarioMimic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitateTarget.o: ../scenarios/ScenarioImitateTarget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpMACEDPG.o: ../scenarios/ScenarioExpMACEDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioImitateTarget.o: ../scenarios/DrawScenarioImitateTarget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrain.o: ../scenarios/DrawScenarioTrain.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioMimicEval.o: ../scenarios/ScenarioMimicEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExp.o: ../scenarios/ScenarioExp.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainCacla.o: ../scenarios/ScenarioTrainCacla.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitateStepEval.o: ../scenarios/ScenarioImitateStepEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioSimChar.o: ../scenarios/ScenarioSimChar.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioKinMotion.o: ../scenarios/ScenarioKinMotion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpLoco.o: ../scenarios/ScenarioExpLoco.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainMACEDPG.o: ../scenarios/ScenarioTrainMACEDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTerrainRL.o: ../scenarios/DrawScenarioTerrainRL.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioHikeEval.o: ../scenarios/ScenarioHikeEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainDMACE.o: ../scenarios/ScenarioTrainDMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioSoccerEval.o: ../scenarios/ScenarioSoccerEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainMACEDPG.o: ../scenarios/DrawScenarioTrainMACEDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTerrainViewer.o: ../scenarios/DrawScenarioTerrainViewer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioImitateStepEval.o: ../scenarios/DrawScenarioImitateStepEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Scenario.o: ../scenarios/Scenario.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainMACE.o: ../scenarios/DrawScenarioTrainMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainHike.o: ../scenarios/ScenarioTrainHike.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioJump.o: ../scenarios/ScenarioJump.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioClimb.o: ../scenarios/DrawScenarioClimb.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioImitateStep.o: ../scenarios/DrawScenarioImitateStep.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainDPG.o: ../scenarios/ScenarioTrainDPG.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpMACE.o: ../scenarios/ScenarioExpMACE.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioLocoEval.o: ../scenarios/DrawScenarioLocoEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioTrainSoccer.o: ../scenarios/ScenarioTrainSoccer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioExpImitateTarget.o: ../scenarios/ScenarioExpImitateTarget.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitateTargetEval.o: ../scenarios/ScenarioImitateTargetEval.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawScenarioTrainHike.o: ../scenarios/DrawScenarioTrainHike.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScenarioImitateStep.o: ../scenarios/ScenarioImitateStep.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
