# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/terrainrlRender
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlRender.so
  DEFINES   += -DDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlUtil -lterrainrlAnim -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_debug -lBulletCollision_gmake_x64_debug -lLinearMath_gmake_x64_debug -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW -lGLU
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlUtil.so ../lib/libterrainrlAnim.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/terrainrlRender
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlRender.so
  DEFINES   += -DNDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -O2 -m32 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m32 -L/usr/lib32 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlUtil -lterrainrlAnim -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_release -lBulletCollision_gmake_x64_release -lLinearMath_gmake_x64_release -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW -lGLU
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlUtil.so ../lib/libterrainrlAnim.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/terrainrlRender
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlRender.so
  DEFINES   += -DDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlUtil -lterrainrlAnim -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_debug -lBulletCollision_gmake_x64_debug -lLinearMath_gmake_x64_debug -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW -lGLU
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlUtil.so ../lib/libterrainrlAnim.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/terrainrlRender
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libterrainrlRender.so
  DEFINES   += -DNDEBUG -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_WARNINGS -DCPU_ONLY -DGOOGLE_GLOG_DLL_DECL= -DENABLE_TRAINING -D_LINUX_
  INCLUDES  += -I.. -I../external/Bullet/src -I../external -I../external/jsoncpp/include -I../external/caffe/include -I../external/caffe/build/src -IC:/Program\ Files\ \(x86\)/boost/boost_1_58_0 -I../external/3rdparty/include/hdf5 -I../external/3rdparty/include -I../external/3rdparty/include/openblas -I../external/3rdparty/include/lmdb -I/usr/local/cuda/include -I../external/OpenCV/include -I../external/caffe/src -I/usr/include/hdf5/serial
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -O2 -m64 -fPIC -ggdb -fPIC -std=c++0x -ggdb `pkg-config --cflags gl` `pkg-config --cflags glu`
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -m64 -L/usr/lib64 -Wl,-rpath,/disk2/MotionDev/TerrainTest/OKMIMIC/TerrainRLSim/lib `pkg-config --libs gl` `pkg-config --libs glu` -L../external/Bullet/bin -L../external/jsoncpp/build/debug/src/lib_json -L../external/caffe/build/lib -L../lib
  LIBS      += -lterrainrlUtil -lterrainrlAnim -lX11 -ldl -lpthread -lBulletDynamics_gmake_x64_release -lBulletCollision_gmake_x64_release -lLinearMath_gmake_x64_release -ljsoncpp -lboost_system -lcaffe -lglog -lhdf5_serial_hl -lhdf5_serial -lglut -lGLEW -lGLU
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libterrainrlUtil.so ../lib/libterrainrlAnim.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/TextureUtil.o \
	$(OBJDIR)/IBuffer.o \
	$(OBJDIR)/GraphUtil.o \
	$(OBJDIR)/HosekSkyModel.o \
	$(OBJDIR)/Camera.o \
	$(OBJDIR)/DrawWorld.o \
	$(OBJDIR)/PostProcessor.o \
	$(OBJDIR)/TextureDesc.o \
	$(OBJDIR)/GBuffer.o \
	$(OBJDIR)/OFFParser.o \
	$(OBJDIR)/DrawMusculotendonUnit.o \
	$(OBJDIR)/DrawGround.o \
	$(OBJDIR)/VertexBuffer.o \
	$(OBJDIR)/DrawSimCharacter.o \
	$(OBJDIR)/DrawKinTree.o \
	$(OBJDIR)/DrawUtil.o \
	$(OBJDIR)/DrawMesh.o \
	$(OBJDIR)/Shader.o \
	$(OBJDIR)/DrawCharacter.o \
	$(OBJDIR)/DrawObj.o \
	$(OBJDIR)/ShadowMap.o \
	$(OBJDIR)/SkyBox.o \
	$(OBJDIR)/DrawPerturb.o \
	$(OBJDIR)/MeshUtil.o \
	$(OBJDIR)/lodepng.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking terrainrlRender
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning terrainrlRender
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/TextureUtil.o: ../render/TextureUtil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/IBuffer.o: ../render/IBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GraphUtil.o: ../render/GraphUtil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HosekSkyModel.o: ../render/HosekSkyModel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Camera.o: ../render/Camera.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawWorld.o: ../render/DrawWorld.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PostProcessor.o: ../render/PostProcessor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TextureDesc.o: ../render/TextureDesc.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GBuffer.o: ../render/GBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OFFParser.o: ../render/OFFParser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawMusculotendonUnit.o: ../render/DrawMusculotendonUnit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawGround.o: ../render/DrawGround.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VertexBuffer.o: ../render/VertexBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawSimCharacter.o: ../render/DrawSimCharacter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawKinTree.o: ../render/DrawKinTree.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawUtil.o: ../render/DrawUtil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawMesh.o: ../render/DrawMesh.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Shader.o: ../render/Shader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawCharacter.o: ../render/DrawCharacter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawObj.o: ../render/DrawObj.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ShadowMap.o: ../render/ShadowMap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkyBox.o: ../render/SkyBox.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DrawPerturb.o: ../render/DrawPerturb.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MeshUtil.o: ../render/MeshUtil.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/lodepng.o: ../external/LodePNG/lodepng.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
